version: '3.8'
services:
  client:
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8090:8090'
    volumes:
      - '/pro-react-admin/node_modules'
      - './:/pro-react-admin'
